package com.sepim.springboot.mapper;

import com.sepim.springboot.entity.TestGenerator;
import com.sepim.springboot.entity.example.TestGeneratorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    long countByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int deleteByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int insert(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int insertSelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    List<TestGenerator> selectByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    TestGenerator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestGenerator record);
}