server:
  servlet:
    session:
      timeout: 600

  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sepim?serverTimezone=UTC
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.phage.boot

      filters: stat,wall

      stat-view-servlet: #监控页的功能
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false\

      web-stat-filter:
        enabled: true
        url-pattern: /*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
    #邮箱验证码配置
  mail:
      #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.qq.com
      #服务协议
    protocol: smtp
      # 编码集
    default-encoding: UTF-8
      #发送邮件的账户
    username: 470565129@qq.com
      #授权码
    password: gihqwkpaaijnbgfc
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jdbc:
    template:
      query-timeout: 3

  redis:
#    Redis服务器地址
    host: 192.168.102.100
#    端口号
    port: 6379
#    数据库索引（默认为0）
    database: 0
#    连接超时时间（毫秒）
    timeout: 1800000
    lettuce:
      pool:
#        连接池最大连接数（使用负值表示没有限制）
        max-active: 20
#        最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
#        连接池的最大空闲连接
        max-idle: 5
#        连接池的最小空闲连接
        min-idle: 0

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


